#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

# As we use a custom JVM (not the one provided by openshift), we update the global variables
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_31
export PATH=$JAVA_HOME/bin:$PATH

export LOG=$OPENSHIFT_LOG_DIR/out.log

nohup java -Dhttp.port=$OPENSHIFT_DIY_PORT -Dhttp.address=$OPENSHIFT_DIY_IP -jar $OPENSHIFT_REPO_DIR/application/*-fat.jar > $LOG 2>&1 &

echo $! > $OPENSHIFT_REPO_DIR/RUNNING_PID
